### ISSUE TITLE
ConfigureLauncher(...).launch is not a function

### ISSUE THREAD

**Issue by pvadwala** [HuddleEng/Muppeteer#34]
Firstly, thanks for creating this project. :+1: 

I am trying to run a very basic test with muppeteer using CLI but getting below error. Can you please help me resolve it? Let me know if I am doing something wrong. 
`TypeError: ConfigureLauncher(...).launch is not a function`

Attached is a screenshot. 

![image](https://user-images.githubusercontent.com/18431709/42119071-b637d6fc-7c4b-11e8-95c1-3075ffa9b8d6.png)

**Comment by gidztech** [comment]
Hi there. Thanks for pointing this out! I have some missing test coverage for the CLI module. I recently made `ConfigureLauncher` async, which means we need to wait for that `Promise` to resolve before doing the launch. I updated the non-CLI usage, but forgot to update the CLI, hence the error. 

I will aim to fix this in the next day or two, and also importantly add the missing test coverage for this.

**Comment by quangdng** [comment]
@gidztech Hi there, is there any news for this? Looks like it is still broken in master.

**Comment by gidztech** [comment]
I've done some refactoring and organising of the project, and fixed this async issue. The Launcher function has changed a bit.  `lib/launcherCli.js` is the new path for the CLI. I accepted the breaking change since I believe usage to be low.

Let me know if there's any other problems.
